services:
  graphql:
    build: 
      context: ./entraid_mock
    container_name: graphql
    ports:
      - "4711:4711"
    environment:
      - PORT=4711
      - USE_MOCK_AUTH=true
      - TENANT_ID=your-tenant-id
      - CLIENT_ID=your-client-id
      - CLIENT_SECRET=your-client-secret
    volumes:
      - ./entraid_mock:/app
    restart: unless-stopped
    networks:
      - fido
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app.py:/app/app.py
    networks:
      - fido
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fido
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - fido
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mariadb
    networks:
      - fido

networks:
  fido:

volumes:
  mariadb_data: