name: Build Python App on Windows

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest  # Or whatever your test command is

      - name: Build executable with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --noconsole --onefile --windowed ykbatch.py

      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: ykbatch
          path: dist/ykbatch.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ykbatch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

