name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and build
        run: |
          python -m pip install --upgrade pip
          pip install -r fidobulk/requirements.txt
          pip install pywin32
          pip install pyinstaller
          pyinstaller fidobulk/main.py --onefile --name=fidobulk

      - name: Upload executable to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/fidobulk.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
