# .github/workflows/build.yml
name: Build Python App

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Build EXE
        working-directory: ./app
        run: |
          pip install pyinstaller
          pyinstaller ykbatch.py --onefile

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ykbatch
          path: app/dist/ykbatch.exe
